# This file is generated by Anlogic Timing Wizard. 19 03 2020

#Created Clock
create_clock -name "CK_24M" -period 41.666666 [get_ports {CK24M_i}] -waveform {0 28.83333333}

derive_pll_clocks -gen_basic_clock
